#!/bin/csh -f

#
# Install
#

cd `dirname $0` && source ./Configuration

#echo "Running cacheload unit tests"
#cd unittest
#./all_tests.csh
#if ( $status ) then
#    exit 1
#endif
#cd ..

if ( ! -d ${MGICACHEDIR} ) then
	mkdir -p ${MGICACHEDIR}
endif

if ( ! -d ${MGICACHEINDIR} ) then
	mkdir -p ${MGICACHEINDIR}
endif

if ( ! -d ${MGICACHEBCPDIR} ) then
	mkdir -p ${MGICACHEBCPDIR}
endif

if ( ! -d ${MGICACHELOGDIR} ) then
	mkdir -p ${MGICACHELOGDIR}
endif

